-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

use catalog pipeline

-- COMMAND ----------


select s.customer_id, c.customer_email, c.customer_city,  round(sum(total_amount)) as total_sales
from silver.sales_cleaned s
join gold.customers_active c
on s.customer_id = c.customer_id
group by s.customer_id, customer_email, customer_city
order by total_sales desc

-- COMMAND ----------

select 
  s.customer_id, 
  c.customer_email, 
  c.customer_city,  
  p.product_id,
  p.product_name,
  round(sum(s.total_amount)) as total_sales
from silver.sales_cleaned s
join gold.customers_active c
  on s.customer_id = c.customer_id
join silver.products_silver p
  on s.product_id = p.product_id
group by s.customer_id, c.customer_email, c.customer_city, p.product_id, p.product_name
order by total_sales desc

-- COMMAND ----------

select * from gold.topcustomers 
order by customer_id desc
